default_config:

homeassistant:
  name: Vilnius Live Cameras Test
  unit_system: metric
  time_zone: Europe/Vilnius
  country: LT
  external_url: http://localhost:8124
  internal_url: http://localhost:8124

logger:
  default: warning
  logs:
    custom_components.vilnius_live_cameras: debug
